version: '3.9'
services:
  app_registrations_notifier_cron:
    container_name: app_registrations_notifier_cron
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app/:/app